# Generated by Django 4.1 on 2025-05-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0003_profile_email_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
